# Site settings
title: Evalbrink
email: hopeverse@gmail.com
description: "关于前端、关于信念、关于自由"
permalink: /:year/:month/:day/:title.html
baseurl: ""
url: "http://liutianzhu.me"
atom-baseurl: "http://liutianzhu.me"
author: "Liutianzhu"

# Build settings
# permalink: date

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks,no_intra_emphasis,strikethrough,no_intra_emphasis,autolink,tables]

#duoshuo
  comments :
    provider : duoshuo
    duoshuo :
      short_name : hopeverse

navigations:
  - title: Archive
    class: fa fa-tags
    href: /archive/
  - title: Categories
    class: fa fa-user
    href: /categories/
  - title: Tags
    class: fa fa-film
    href: /tags/
  - title: About
    class: fa fa-list-ul
    href: /about/
  - title: Rss
    class: fa fa-rss
    href: /atom.xml
